#!/bin/sh
# One-time setup for Fly.io deployment
# Run: ./setup.sh (from the relay/ directory)

set -eu

echo "=== Generating secrets ==="
HMAC_SECRET=$(openssl rand -hex 32)
API_KEY=$(openssl rand -hex 32)

echo ""
echo "=== Step 1: Create the Fly app ==="
fly launch --no-deploy

echo ""
echo "=== Step 2: Set secrets ==="
fly secrets set HMAC_SECRET_KEY="$HMAC_SECRET" API_KEY="$API_KEY"

echo ""
echo "=== Step 3: Deploy ==="
fly deploy

echo ""
echo "=== Step 4: Generate connection token ==="
RELAY_TOKEN=$(fly ssh console -c "centrifugo gentoken -c /etc/centrifugo/config.json -u bridge -t 3153600000" 2>/dev/null)

echo ""
echo "============================================================"
echo "  RELAY DEPLOYED — SAVE THESE VALUES"
echo "============================================================"
echo ""
echo "  Relay URL:"
echo "    wss://fidobridge-relay.fly.dev/connection/websocket"
echo ""
echo "  Connection JWT (RELAY_TOKEN):"
echo "    $RELAY_TOKEN"
echo ""
echo "  Relay secrets (for reference / key rotation):"
echo "    HMAC_SECRET_KEY: $HMAC_SECRET"
echo "    API_KEY:         $API_KEY"
echo ""
echo "  E2EE session key: generated by 'fido-daemon pair' (see below)"
echo ""
echo "============================================================"
echo "  NEXT STEPS"
echo "============================================================"
echo ""
echo "  1. Pair daemon + phone:"
echo ""
echo "       cd linux-fido-daemon"
echo "       fido-daemon pair"
echo "       # Scan the QR code with the Android app"
echo ""
echo "  2. Run the daemon:"
echo ""
echo "       export FIDO2_RELAY_URL=wss://fidobridge-relay.fly.dev/connection/websocket"
echo "       export FIDO2_RELAY_TOKEN=$RELAY_TOKEN"
echo "       # + FIDO2_SESSION_KEY_B64 and FIDO2_CHANNEL_ID from pairing"
echo "       fido-daemon"
echo ""
echo "============================================================"
